INCLUDE_DIRS := /usr/local/include 
LIBRARY_DIRS := /usr/local/lib 

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Enable OpenMP (LINUX only)
USE_OPENMP := 1

# Enable LBFGS optimizer
USE_LBFGS := 1
USE_NRBM := 1

# enable pretty build (comment to see full commands)
Q ?= @
